$('.owl-carousel').owlCarousel({
        items:1,
        merge:false,
        loop:true,
        margin:40,
        autoplay:true,
        video:false,
        lazyLoad:true,
        center:true,
        nav:true,
        dots:true,
        responsive:{
            520:{
                items:1
            },
            800:{
                items:2
            },
            1024:{
                items:3
            }
        }
    })